### ISSUE TITLE
Rack::Recaptcha::Helpers recaptcha_valid? exceptions with rails 2.3.8

### ISSUE THREAD

**Issue by ionous** [achiurizo/rack-recaptcha#1]
i'm new to rails, rack, ruby, and git/hub - so this could be user error.
within my rails controller i tried to use recaptcha_valid? but got an exception that 'env' was unknown. at the point i wanted to use it -- 'env' wasn't in the current scope, but.. after some reading up on rails on rack... 'env' does seem to live in the 'request'.

here's the change i made that seems to work, if i can figure out how to clone,branch,etc :) i will see if i can put a patch together.

```
  def recaptcha_valid?
    return env['recaptcha.valid'] if defined? env
    # when a rails controller is processing, the env needs to be pulled from request
    return request.env['recaptcha.valid'] if defined? request and defined? request.env
  end
```

**Comment by achiurizo** [comment]
hey ionous,
i pushed a fix for this here 91439ce9a2e5b9102533a99c80f1a5f4957de5f7. thanks for the catch!
