### ISSUE TITLE
Rack::Recaptcha::Helpers recaptcha_valid? exceptions with rails 2.3.5

### ISSUE THREAD

**Issue by wyzguy** [achiurizo/rack-recaptcha#10]
I'm seeing the following error with rack-recaptcha (0.5.0) and rails (2.3.5).

The backend application (process 28473) did not send a valid HTTP response; instead, it sent nothing at all. It is possible that it has crashed; please check whether there are crashing bugs in this application.
**\* Exception NameError in PhusionPassenger::Rack::ApplicationSpawner (undefined local variable or method `request' for #<CASServer::Controllers::Register:0x7f779cfbed00>) (process 28473):
        from /var/lib/gems/1.8/gems/rack-recaptcha-0.5.0/lib/rack/recaptcha/helpers.rb:67:in`recaptcha_valid?'
        from ./lib/casserver/dreamu_controllers.rb:277:in `post'

**Comment by wyzguy** [comment]
I was able to get around this by going back to rack-recaptcha (0.2.2) and modifying the 'recaptcha.rb' with the following changes.  Would like to get rack-recaptcha (0.5.0) working.

'#    API_URL         = 'http://api.recaptcha.net''
'#    API_SECURE_URL  = 'https://api-secure.recaptcha.net''
'#    VERIFY_URL      = 'http://api-verify.recaptcha.net/verify''
'    API_URL         = 'http://www.google.com/recaptcha/api''
'    API_SECURE_URL  = 'https://www.google.com/recaptcha/api''
'    VERIFY_URL      = 'http://www.google.com/recaptcha/api/verify''

**Comment by achiurizo** [comment]
this seems somewhat related to this issue here: https://github.com/achiu/rack-recaptcha/issues/1 which has the helper using `request` to solve the issue of accessing `env`. perhaps you could try upgrading to see if this fixes your issue?
