### ISSUE TITLE
Rails 3.1.0 issue with asset pipeline

### ISSUE THREAD

**Issue by stevenkolstad** [achiurizo/rack-recaptcha#15]
Image doesn't display with asset pipeline enabled.

When it is disabled it doesn't render anything, except this message: Input error: Invalid referer.

Actually, it works fine in development, but production it doesn't.

Thanks,

Steve

**Comment by eric-hu** [comment]
Did you create more than one account with Recaptcha?  You can check by visiting [the homepage](http://www.google.com/recaptcha) and clicking "My Account"

You need to create a separate account for production mode, unless you're running off localhost for that too :P

From the Recaptcha account page:

_reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys._

If you were going off the instructions on the front page, you should put the following line in production.rb

```
   config.middleware.use Rack::Recaptcha, :public_key => 'KEY', :private_key => 'SECRET'
```

You have this in application.rb already for your localhost settings.  Your production.rb public/private key pair will override the application.rb one.

Let me know if that works.

**Comment by eric-hu** [comment]
So these are two separate issues.  The "Invalid referer." message is what
you see when you try to access Recaptcha from an invalid domain name for the
public/private keypair you generated.

I'll look into what's necessary to put the image in a default asset
pipeline.

**Comment by eric-hu** [comment]
@agentrock Did you get this working by creating a new account for your production domain?

The image should actually come from Google, so I believe it's independent of the asset pipeline.  If you're still having issues with the asset pipeline enabled, please let me know

**Comment by stevenkolstad** [comment]
I decided to go with negative-captcha for now. 

I was using the production site variables, even in development. Maybe that was the problem, IDK.

I'll take a second look if negative-captcha doesn't slow down the bots.

Thank you for all of your help so far.
