### ISSUE TITLE
I am getting this error after setting desired configurations !

### ISSUE THREAD

**Issue by bournenapster** [achiurizo/rack-recaptcha#16]
bourne@bourne-Latitude-E6400:~/Documents/sandy/e2$ rake db:create --trace
rake aborted!
uninitialized constant ApplicationController::Rack
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/ext/module.rb:36:in `const_missing'
/home/bourne/Documents/sandy/e2/config/application.rb:3:in`module:ApplicationController'
/home/bourne/Documents/sandy/e2/config/application.rb:2:in `<top (required)>'
/home/bourne/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
/home/bourne/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/bourne/Documents/sandy/e2/Rakefile:5:in`<top (required)>'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in`load_rakefile'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:82:in`block in load_rakefile'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:81:in`load_rakefile'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `load'
/home/bourne/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in`<main>'
bourne@bourne-Latitude-E6400:~/Documents/sandy/e2$ 

on every command i execute i get errors ....without recaptcha it works fine ?

**Comment by bournenapster** [comment]
A correct way of implementing config/application.rb ========>

require File.expand_path('../boot', **FILE**)

require 'rails/all'

if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end

module E4
  class Application < Rails::Application

  config.gem 'rack-recaptcha', :lib => 'rack/recaptcha'
  config.middleware.use Rack::Recaptcha, :public_key => '6Ldgd8kSAAAAADAbx5rClTDDj47mDOH7BQuEbiyM', :private_key => '6Ldgd8kSAAAAAO0Iav9X2IKNpHLcLk7JpxVqwiCz'

# Settings in config/environments/\* take precedence over those specified here.

```
# Application configuration should go into files in config/initializers
# -- all .rb files in that directory are automatically loaded.

# Custom directories with classes and modules you want to be autoloadable.
# config.autoload_paths += %W(#{config.root}/extras)

# Only load the plugins named here, in the order given (default is alphabetical).
# :all can be used as a placeholder for all plugins not explicitly named.
# config.plugins = [ :exception_notification, :ssl_requirement, :all ]

# Activate observers that should always be running.
# config.active_record.observers = :cacher, :garbage_collector, :forum_observer

# Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
# Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
# config.time_zone = 'Central Time (US & Canada)'

# The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
# config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
# config.i18n.default_locale = :de

# Configure the default encoding used in templates for Ruby 1.9.
config.encoding = "utf-8"

# Configure sensitive parameters which will be filtered from the log file.
config.filter_parameters += [:password]

# Enable the asset pipeline
config.assets.enabled = true

# Version of your assets, change this if you want to expire all your assets
config.assets.version = '1.0'
```

  end

## application_helper.rb or whatever helper you want it in.

module ApplicationHelper
  include Rack::Recaptcha::Helpers
end

## application_controller.rb or whatever controller you want it in.

module ApplicationController
  include Rack::Recaptcha::Helpers
end
#*********************_bewareof this end this was causing my error ***_*******
end

**Comment by eric-hu** [comment]
I think you meant `application.rb` instead of `application_controller.rb`.  I was able to reproduce your error.  I'll update the docs to be a little more descriptive.  Thanks for pointing this out.
