### ISSUE TITLE
Rails example

### ISSUE THREAD

**Issue by eric-hu** [achiurizo/rack-recaptcha#5]
Generating the recaptcha tag using Rails 3.0.5 required that I use "raw".  Otherwise, this would be displayed as text on the page:

> <script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=..."\> </script>

```
<%= form_tag('/users') do %>
  <%= raw recaptcha_tag(:challenge)%>
  <%= submit_tag "Submit" %>
<% end %>
```

 This took me a bit of time to google so I thought I'd put it up here so others can start using this gem more easily.  I'm still relatively new to rails, so perhaps there's an easier or more elegant way to do this.

**Comment by achiurizo** [comment]
updated the README with the need to include the #raw helper. thanks
