### ISSUE TITLE
Rails: Rack-recaptcha with form_for

### ISSUE THREAD

**Issue by eric-hu** [achiurizo/rack-recaptcha#6]
I was able to use this gem with "form_for", instead of "form_tag":

```
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  ...
  <p>
  <%= raw f.recaptcha_tag(:challenge) %>
  </p>
  <p><%= f.submit "Sign up" %></p>

<% end %>
```

Possibly something else to include on the front page for new users?

**Comment by achiurizo** [comment]
i tried it with the form_tag and it seemed to work. what exactly wasn't working?

**Comment by eric-hu** [comment]
Sorry, I didn't mean to suggest this was a bug, just that it's an alternative to using form_tag.  I was able to get it working with both, too.  My initial impression on reading the source page was that I could only use form_tag.

**Comment by achiurizo** [comment]
Oh I see. I went with the general assumption that if I posted the example using form_tag, most would see that form_for would also work. But thanks for the note. closing ticket.
